# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Renee
tagline:          'A Jekyll theme'
description:      'Renee Test Blog'
url:              https://renee-sample.github.io/test.blog/
baseurl:          /test.blog/

author:
  name:           'Renee'
  url:            http://renee13wi.cafe24.com/html/main.php

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
